[tool.towncrier]
package = "aioredis"
filename = "docs/changelog.md"
directory = "CHANGES/"
start_string = "# Changelog\n"
issue_format = "#{issue}"
underlines = ["", ""]
template = ".towncrier.md.jinja"
title_format = "## {version} - ({project_date})"

[tool.pytest.ini_options]
markers = [
    "hiredis_parser: mark a test as using hiredis parser",
    "python_parser: mark a test as using python parser",
    "connection_pool: mark a test as using connection_pool client",
    "single_connection: mark a test as using single connection client",
]
